name: Deploy to Dev Environment

on:
  push:
    branches:
      - feature-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test.py

    - name: Deploy to Vercel (Dev)
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npx vercel --prod --scope=<your-vercel-scope> --token=$VERCEL_TOKEN --confirm --prod
