name: CI - Staging

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u farheenmalik01 --dckr_pat_MMTObk4P11P_nayYd2I-QTb5K8o-stdin


      - name: Build Docker Image
        run: |
          docker build -t mlopsassignment1:latest .

      - name: Push Docker Image
        run: |
          docker tag mlopsassignment1 farheenmalik01/mlopsassignment1:stage
          docker push farheenmalik01/mlopsassignment1:stage

      - name: Deploy to Staging
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          curl -sL https://vercel.com/download -o vercel.zip
          unzip vercel.zip
          ./vercel login $VERCEL_TOKEN
          ./vercel --prod --confirm --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --org $VERCEL_ORG_ID